# Generated by Django 4.2.4 on 2023-11-13 00:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0003_customersupport_delete_contact"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customersupport",
            name="address",
        ),
    ]
