# Generated by Django 4.2.4 on 2023-11-13 13:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0004_remove_customersupport_address"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customersupport",
            name="user",
        ),
        migrations.AddField(
            model_name="customersupport",
            name="name",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
