# Generated by Django 4.2.4 on 2023-11-18 19:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("shops", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="shop",
            name="description",
        ),
        migrations.AddField(
            model_name="shop",
            name="score",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="shop",
            name="user",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="shop",
            name="imagen",
            field=models.ImageField(blank=True, null=True, upload_to="shops/"),
        ),
        migrations.AlterField(
            model_name="shop",
            name="name",
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
