# Generated by Django 4.2.4 on 2023-10-03 22:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("categorias", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="categoria",
            name="imagen",
            field=models.ImageField(blank=True, null=True, upload_to="categorias"),
        ),
        migrations.AlterField(
            model_name="categoria",
            name="slug",
            field=models.SlugField(blank=True, null=True),
        ),
    ]
