# Generated by Django 4.2.4 on 2023-10-11 00:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0003_reviews"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="slug",
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
