# Generated by Django 4.2.4 on 2023-11-18 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("shops", "0002_remove_shop_description_shop_score_shop_user_and_more"),
        ("products", "0007_alter_reviews_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="shop",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to="shops.shop"
            ),
        ),
    ]
