# Generated by Django 4.2.4 on 2023-12-09 16:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0009_cart_cartitem"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cartitem",
            name="quantity",
            field=models.IntegerField(default=0),
        ),
    ]
